services:
  - type: web
    name: amc10-homework
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python3 server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: "10000"